/**
 * Single source of truth for business facts (NAP, hours, geo, founding year).
 *
 * Every place that shows or emits these facts (footer, homepage CTA, contact
 * page fallback, Impressum, JSON-LD, geo meta tags, SEO copy) must import them
 * from here. Search engines cross-check NAP (name, address, phone) between the
 * website, structured data and the Google Business Profile, so the values here
 * should be copied *exactly* from the verified Google Business Profile.
 *
 * Values marked TODO still need confirmation from the client.
 */

export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://braunundeyer.de').replace(/\/$/, '');

export const SITE = {
  name: 'Braun & Eyer Architekten',
  legalName: 'Braun & Eyer Architekten GbR',
  alternateNames: ['Braun und Eyer Architekten', 'Braun & Eyer'],

  address: {
    // TODO(client): the official street name is "Mainzer Straße" (OpenStreetMap);
    // use whatever spelling the Google Business Profile uses, everywhere.
    street: 'Mainzerstraße 29',
    postalCode: '66111',
    city: 'Saarbrücken',
    region: 'Saarland',
    regionCode: 'SL',
    country: 'DE',
    countryName: 'Deutschland',
  },

  phone: {
    display: '+49 681 95417488',
    national: '0681 95417488',
    e164: '+4968195417488', // use in tel: links
  },
  fax: {
    display: '+49 681 95417487',
    e164: '+4968195417487',
  },
  email: 'info@braunundeyer.de',

  // TODO(client): confirm the founding year. JSON-LD and metadata use 1999;
  // older copy (about.json, AboutUsClient fallbacks) said 1995.
  foundingYear: '1999',

  // TODO(client): confirm coordinates against the Google Business Profile pin.
  // OpenStreetMap geocodes Mainzer Straße 29 at roughly 49.2310, 7.0015
  // (about 1 km from the values below, which are the ones the site used so far).
  geo: {
    latitude: 49.2341,
    longitude: 6.9895,
  },

  // TODO(client): confirm opening hours. This set matches the hours currently
  // maintained in the CMS (contact-settings) and shown on /kontakt.
  // Shape mirrors the CMS `openingHours` entries so the contact page can use it
  // as its fallback.
  openingHours: [
    { day: 'Monday', dayDe: 'Montag', open: '09:00', close: '18:00', closed: false },
    { day: 'Tuesday', dayDe: 'Dienstag', open: '09:00', close: '18:00', closed: false },
    { day: 'Wednesday', dayDe: 'Mittwoch', open: '09:00', close: '18:00', closed: false },
    { day: 'Thursday', dayDe: 'Donnerstag', open: '09:00', close: '18:00', closed: false },
    { day: 'Friday', dayDe: 'Freitag', open: '09:00', close: '17:00', closed: false },
    { day: 'Saturday', dayDe: 'Samstag', open: '', close: '', closed: true },
    { day: 'Sunday', dayDe: 'Sonntag', open: '', close: '', closed: true },
  ],

  founders: [
    { name: 'Christian F. Braun', jobTitle: 'Dipl.-Ing. Architekt' },
    { name: 'Patric Eyer', jobTitle: 'Dipl.-Ing. Architekt' },
  ],

  // Stated in the Impressum (zuständige Kammer).
  chamber: {
    name: 'Architektenkammer des Saarlandes',
    url: 'https://www.aksaarland.de',
  },

  // TODO(client): only add profile URLs that really exist and belong to the
  // office (e.g. the Google Business Profile share URL, a verified Instagram or
  // LinkedIn page). Leave empty rather than linking to bare platform home pages.
  // Used by the footer social icons and JSON-LD `sameAs`.
  socialProfiles: [
    // { platform: 'Instagram', url: 'https://www.instagram.com/...' },
  ],

  // Brand assets in /public (generated by scripts/generate-brand-assets.mjs).
  assets: {
    logo: { path: '/logo.png', width: 600, height: 600 },
    ogImage: { path: '/og-image.jpg', width: 1200, height: 630 },
  },
};

/** Absolute URL for a site path ("/logo.png" -> "https://braunundeyer.de/logo.png"). */
export function absoluteUrl(path = '') {
  if (!path) return SITE_URL;
  if (/^https?:\/\//.test(path)) return path;
  return `${SITE_URL}${path.startsWith('/') ? '' : '/'}${path}`;
}

/**
 * Public, absolute URL for a CMS upload. The API layer prefixes uploads with the
 * internal Docker host (http://backend:3001/uploads/...), which must never leak
 * into og:image or JSON-LD. Next.js proxies /uploads/* to the backend, so the
 * public URL is SITE_URL + "/uploads/...".
 */
export function publicAssetUrl(url) {
  if (!url || typeof url !== 'string') return null;
  const idx = url.indexOf('/uploads/');
  if (idx !== -1) return `${SITE_URL}${url.slice(idx)}`;
  if (url.startsWith('/')) return `${SITE_URL}${url}`;
  if (/^https?:\/\//.test(url) && !/localhost|backend:3001/.test(url)) return url;
  return null;
}

/**
 * CMS URL for the footer triple-click admin shortcut. In production it is never
 * allowed to point at localhost, whatever the build-time env contains.
 */
export function getCmsUrl(hostname) {
  const PROD_CMS = 'https://cms.braunundeyer.de';
  const fromEnv = process.env.NEXT_PUBLIC_CMS_URL;
  const isLocalUrl = (u) => /localhost|127\.0\.0\.1/.test(u || '');
  if (process.env.NODE_ENV === 'production') {
    return fromEnv && !isLocalUrl(fromEnv) ? fromEnv : PROD_CMS;
  }
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return 'http://localhost:4029';
  }
  return fromEnv || PROD_CMS;
}
