/**
 * Interface copy for the redesigned site, per language.
 *
 * Rules (design REVIEW §2.7): sentence case, plain verbs, say what was built,
 * where and when. No invented facts, stats, testimonials or promises: anything
 * factual (founding year, address, founders, chamber) is interpolated from
 * lib/site.js. Empty/error states say what happened and what to do next.
 *
 * The objects are plain data (strings, [one, other] plural pairs and
 * "{placeholder}" templates) so a subset can be passed from server components
 * to client components as props. Use `fmt()` / `plural()` from lib/fmt.js.
 *
 * Missing keys in a language fall back to German (deep merge in getUiCopy).
 */
import { SITE } from './site';

const Y = SITE.foundingYear;

const de = {
  common: {
    skip: 'Zum Inhalt springen',
    menu: 'Menü',
    close: 'Schließen',
    language: 'Sprache',
    mainNav: 'Hauptnavigation',
    homeLabel: `${SITE.name}, zur Startseite`,
    breadcrumbs: 'Brotkrumen',
    images: ['Aufnahme', 'Aufnahmen'],
    imageN: 'Aufnahme {n}',
    imageOf: 'Aufnahme {n} von {total}',
    enlarge: '{label} vergrößern',
    viewProject: 'Projekt ansehen',
  },
  categories: {
    neubau: 'Neubau',
    altbausanierung: 'Altbausanierung',
    denkmalschutz: 'Denkmalschutz',
    innenarchitektur: 'Innenarchitektur',
  },
  footer: {
    office: 'Büro',
    contact: 'Kontakt',
    pages: 'Seiten',
    nav: 'Fußzeile',
    cookies: 'Cookie-Einstellungen',
  },
  home: {
    intro: 'Wir planen Neubauten, sanieren Altbauten und begleiten Umbauten unter Denkmalschutz, vom ersten Entwurf bis zur Baubegleitung.',
    since: `Architekturbüro in ${SITE.address.city}, seit ${Y}`,
    heroLink: 'Projekte ansehen',
    playVideo: 'Video abspielen',
    selected: 'Ausgewählte Projekte',
    allProjects: 'Alle Projekte',
    services: 'Leistungen',
    servicesIntro: 'Wir übernehmen die Planung von der ersten Beratung über Entwurf und Bauantrag bis zur Baubegleitung.',
    servicesMore: 'Leistungen und Ablauf im Detail',
    office: 'Das Büro',
    officeLead: `${SITE.name} ist ein Architekturbüro in ${SITE.address.city}, gegründet ${Y}. Christian F. Braun und Patric Eyer führen das Büro gemeinsam.`,
    officeMore: 'Mehr über das Büro',
    team: 'Team',
    contactTitle: 'Sprechen Sie mit uns über Ihr Vorhaben.',
    contactText: 'Rufen Sie an oder schreiben Sie uns kurz, worum es geht: Neubau oder Bestand, Ort, gewünschter Zeitrahmen.',
    contactButton: 'Anfrage schreiben',
    hero: {
      label: 'Projekte im Bild',
      carousel: 'Karussell',
      slide: 'Folie',
      slideOf: '{n} von {total}',
      prev: 'Vorherige Folie',
      next: 'Nächste Folie',
      goTo: 'Folie {n} zeigen',
      pause: 'Automatischen Wechsel anhalten',
      play: 'Automatischen Wechsel starten',
      work: 'Unsere Arbeiten',
      contact: 'Kontakt',
      completed: 'Fertigstellung {year}',
    },
  },
  // Intro overlay on the homepage (first visit per session). The wordmark and
  // the tagline are brand words and stay German in every language.
  entry: {
    label: 'Willkommen',
    enter: 'Enter',
    enterHint: 'Zur Website',
    tagline: ['architektur', 'design'],
  },
  // Decorative background words (CSS-generated, aria-hidden, not indexed).
  typo: {
    architecture: 'architektur', design: 'design', innovation: 'innovation', vision: 'vision', space: 'raum',
    build: 'neubau', renovate: 'sanierung', heritage: 'denkmal', contact: 'kontakt', dialogue: 'dialog',
  },
  projects: {
    intro: 'Eine Auswahl realisierter Projekte aus Neubau, Altbausanierung und Innenarchitektur.',
    filterLabel: 'Kategorie',
    all: 'Alle',
    empty: 'Zurzeit sind keine Projekte veröffentlicht.',
    emptyCategory: 'In dieser Kategorie sind noch keine Projekte veröffentlicht.',
    error: 'Die Projekte konnten nicht geladen werden. Bitte laden Sie die Seite neu.',
    reload: 'Seite neu laden',
    toGallery: 'Alle Aufnahmen in der Galerie',
    galleryHint: 'Alle Fotografien auf einen Blick, nach Kategorie und Jahr gefiltert.',
  },
  project: {
    facts: 'Projektdaten',
    description: 'Projektbeschreibung',
    location: 'Ort',
    year: 'Jahr',
    category: 'Kategorie',
    area: 'Fläche',
    status: 'Status',
    count: 'Aufnahmen',
    viewAll: 'Alle {n} Aufnahmen ansehen',
    openInGallery: 'In der Galerie öffnen',
    sequence: 'Aufnahmen',
    next: 'Nächstes Projekt',
    nextNav: 'Weiteres Projekt',
    back: 'Alle Projekte',
  },
  gallery: {
    intro: 'Fotografien aus realisierten Projekten. Ein Bild öffnet die Vollansicht mit Beschreibung; mit den Pfeiltasten blättern Sie weiter.',
    filter: 'Filter',
    category: 'Kategorie',
    year: 'Jahr',
    allCategories: 'Alle',
    allYears: 'Alle Jahre',
    view: 'Ansicht',
    raster: 'Raster',
    byProject: 'Nach Projekt',
    status: '{n} {images} aus {p} {projects}',
    projectsPlural: ['Projekt', 'Projekten'],
    reset: 'Filter zurücksetzen',
    loading: 'Aufnahmen werden geladen',
    emptyTitle: 'Noch keine Aufnahmen veröffentlicht.',
    emptyText: 'Neue Fotografien erscheinen hier, sobald ein Projekt fertiggestellt und dokumentiert ist. Bis dahin finden Sie unsere Arbeiten mit Beschreibung unter Projekte.',
    toProjects: 'Zu den Projekten',
    filterEmptyTitle: 'Keine Aufnahmen für {what}.',
    filterEmptyFallback: 'diese Auswahl',
    filterEmptyYear: 'aus {year}',
    filterEmptyText: 'Wählen Sie eine andere Kategorie oder ein anderes Jahr.',
    errorTitle: 'Die Aufnahmen konnten nicht geladen werden.',
    errorText: 'Der Bildserver hat nicht geantwortet. Prüfen Sie Ihre Verbindung und laden Sie die Seite neu.',
    reload: 'Seite neu laden',
    moreTitle: 'Ein Projekt im Detail ansehen?',
    moreLink: 'Alle Projekte mit Beschreibung',
    location: 'Ort',
    count: 'Aufnahmen',
    grid: 'Aufnahmen',
  },
  lightbox: {
    dialog: 'Bildansicht',
    close: 'Schließen',
    prev: 'Vorheriges Bild',
    next: 'Nächstes Bild',
    toProject: 'Zum Projekt',
  },
  services: {
    intro: 'Wir begleiten Bauvorhaben von der ersten Beratung über Entwurf und Genehmigung bis zur Baubegleitung, im Neubau ebenso wie im Bestand.',
    list: 'Leistungen',
    timeline: 'Zeitrahmen',
    features: 'Schwerpunkte',
    process: 'Ablauf',
    processIntro: 'Die Planung folgt festen Schritten. Sie wissen jederzeit, was als Nächstes kommt.',
    kinds: 'Bauaufgaben',
    kindsIntro: 'Für diese Gebäudearten planen wir regelmäßig.',
    fallback: [
      { id: 'neubau', title: 'Neubau', description: 'Wohnhäuser, Mehrfamilienhäuser und Geschäftsgebäude, von der Standortanalyse bis zur Abnahme.' },
      { id: 'altbausanierung', title: 'Altbausanierung', description: 'Bestandsaufnahme, Sanierungskonzept und energetische Modernisierung, abgestimmt auf Substanz und Bauphysik des Hauses.' },
      { id: 'denkmalschutz', title: 'Denkmalschutz', description: 'Planung und Genehmigung in Abstimmung mit der Denkmalbehörde, damit ein Umbau den Charakter des Gebäudes erhält.' },
      { id: 'innenarchitektur', title: 'Innenarchitektur', description: 'Raumaufteilung, Material- und Lichtplanung für Büros, Praxen und Wohnungen.' },
    ],
    ctaTitle: 'Sie planen einen Neubau oder einen Umbau?',
    ctaText: 'Schildern Sie uns kurz Ihr Vorhaben. Wir melden uns und vereinbaren ein erstes Gespräch.',
    ctaButton: 'Anfrage schreiben',
  },
  about: {
    lead: `${SITE.name} ist ein Architekturbüro in ${SITE.address.city}. Christian F. Braun und Patric Eyer gründeten das Büro ${Y} und führen es gemeinsam.`,
    text: 'Wir planen Neubauten und Umbauten für private und gewerbliche Bauherren, sanieren Altbauten und Baudenkmäler und gestalten Innenräume. Beide Partner sind Mitglied der Architektenkammer des Saarlandes.',
    facts: 'Das Büro in Zahlen und Fakten',
    founded: 'Gegründet',
    seat: 'Sitz',
    partners: 'Partner',
    chamber: 'Kammer',
    team: 'Team',
    email: 'E-Mail',
    phone: 'Telefon',
    ctaTitle: 'Lernen Sie uns kennen.',
    ctaText: 'Am einfachsten in einem ersten Gespräch über Ihr Vorhaben, telefonisch oder bei uns im Büro.',
    ctaButton: 'Kontakt aufnehmen',
    projectsLink: 'Projekte ansehen',
  },
  contact: {
    intro: 'Rufen Sie an, schreiben Sie eine E-Mail oder nutzen Sie das Formular. Wir melden uns bei Ihnen.',
    address: 'Adresse',
    phone: 'Telefon',
    fax: 'Fax',
    email: 'E-Mail',
    hours: 'Bürozeiten',
    closed: 'geschlossen',
    route: 'Route in Google Maps öffnen',
    online: 'Online',
    form: {
      title: 'Anfrage',
      name: 'Name',
      email: 'E-Mail',
      phone: 'Telefon',
      optional: '(optional)',
      projectType: 'Art des Vorhabens',
      select: 'Bitte wählen',
      types: {
        neubau: 'Neubau',
        altbausanierung: 'Altbausanierung',
        denkmalschutz: 'Denkmalschutz',
        innenarchitektur: 'Innenarchitektur',
        energieberatung: 'Energieberatung',
        beratung: 'Beratung',
        sonstiges: 'Sonstiges',
      },
      timeline: 'Zeitrahmen',
      timelineHint: 'zum Beispiel: Baubeginn im Frühjahr',
      message: 'Nachricht',
      messageHint: 'Worum geht es? Neubau oder Bestand, Ort, Größe.',
      required: 'Felder ohne Zusatz sind Pflichtfelder.',
      privacy: 'Ihre Angaben verwenden wir nur, um Ihre Anfrage zu beantworten. Mehr dazu in der',
      privacyLink: 'Datenschutzerklärung',
      submit: 'Anfrage senden',
      sending: 'Wird gesendet …',
      successTitle: 'Danke, Ihre Nachricht ist angekommen.',
      successText: 'Wir melden uns so bald wie möglich bei Ihnen.',
      another: 'Weitere Nachricht schreiben',
      summary: 'Bitte prüfen Sie die markierten Felder.',
      errName: 'Bitte geben Sie Ihren Namen an.',
      errEmail: 'Bitte geben Sie Ihre E-Mail-Adresse an.',
      errEmailInvalid: 'Diese E-Mail-Adresse ist unvollständig, zum Beispiel name@beispiel.de.',
      errMessage: 'Bitte schreiben Sie eine kurze Nachricht.',
      errSubmit: 'Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie direkt an',
    },
  },
  legal: {
    imprintAside: 'Angaben gemäß § 5 DDG',
    privacyAside: 'Welche Daten diese Website verarbeitet, zu welchem Zweck und welche Rechte Sie haben.',
  },
  cookie: {
    title: 'Cookie-Einstellungen',
    text: 'Wir verwenden Cookies, um Ihre Erfahrung auf unserer Website zu verbessern und anonyme Statistiken zu erfassen. Sie können Ihre Einstellungen jederzeit in der Fußzeile ändern.',
    privacyLink: 'Datenschutzerklärung',
    necessaryOnly: 'Nur notwendige',
    settings: 'Einstellungen',
    acceptAll: 'Alle akzeptieren',
    save: 'Auswahl speichern',
    group: 'Cookie-Kategorien',
    necessary: 'Notwendige Cookies',
    necessaryText: 'Diese Cookies sind für die Grundfunktionen der Website erforderlich und können nicht deaktiviert werden.',
    analytics: 'Analyse-Cookies',
    analyticsText: 'Helfen uns zu verstehen, wie Besucher mit unserer Website interagieren, indem anonyme Informationen gesammelt werden.',
    marketing: 'Marketing-Cookies',
    marketingText: 'Werden verwendet, um Besuchern relevante Werbung und Marketing-Kampagnen anzubieten.',
  },
};

const en = {
  common: {
    skip: 'Skip to content',
    menu: 'Menu',
    close: 'Close',
    language: 'Language',
    mainNav: 'Main navigation',
    homeLabel: 'Braun & Eyer Architects, go to the homepage',
    breadcrumbs: 'Breadcrumbs',
    images: ['photo', 'photos'],
    imageN: 'Photo {n}',
    imageOf: 'Photo {n} of {total}',
    enlarge: 'Enlarge {label}',
    viewProject: 'View project',
  },
  categories: {
    neubau: 'New build',
    altbausanierung: 'Renovation',
    denkmalschutz: 'Listed buildings',
    innenarchitektur: 'Interior design',
  },
  footer: { office: 'Office', contact: 'Contact', pages: 'Pages', nav: 'Footer', cookies: 'Cookie settings' },
  home: {
    intro: 'We design new buildings, renovate existing ones and guide conversions of listed buildings, from the first sketch to site supervision.',
    since: `Architecture office in ${SITE.address.city}, since ${Y}`,
    heroLink: 'View projects',
    playVideo: 'Play video',
    selected: 'Selected projects',
    allProjects: 'All projects',
    services: 'Services',
    servicesIntro: 'We handle the planning from the first consultation through design and building permit to site supervision.',
    servicesMore: 'Services and process in detail',
    office: 'The office',
    officeLead: `Braun & Eyer Architects is an architecture office in ${SITE.address.city}, founded in ${Y}. Christian F. Braun and Patric Eyer run the office together.`,
    officeMore: 'More about the office',
    team: 'Team',
    contactTitle: 'Talk to us about your project.',
    contactText: 'Call us or send a short message about what you have in mind: new build or existing building, location, preferred time frame.',
    contactButton: 'Send an enquiry',
    hero: {
      label: 'Projects in pictures', carousel: 'carousel', slide: 'slide', slideOf: '{n} of {total}',
      prev: 'Previous slide', next: 'Next slide', goTo: 'Show slide {n}',
      pause: 'Pause automatic rotation', play: 'Start automatic rotation',
      work: 'Our work', contact: 'Contact', completed: 'Completed {year}',
    },
  },
  entry: { label: 'Welcome', enterHint: 'Go to the website' },
  typo: {
    architecture: 'architecture', design: 'design', innovation: 'innovation', vision: 'vision', space: 'space',
    build: 'building', renovate: 'renovation', heritage: 'heritage', contact: 'contact', dialogue: 'dialogue',
  },
  projects: {
    intro: 'A selection of completed projects: new buildings, renovation and interior design.',
    filterLabel: 'Category',
    all: 'All',
    empty: 'No projects are published at the moment.',
    emptyCategory: 'No projects have been published in this category yet.',
    error: 'The projects could not be loaded. Please reload the page.',
    reload: 'Reload page',
    toGallery: 'All photos in the gallery',
    galleryHint: 'Every photograph at a glance, filtered by category and year.',
  },
  project: {
    facts: 'Project data', description: 'Project description', location: 'Location', year: 'Year',
    category: 'Category', area: 'Area', status: 'Status', count: 'Photos',
    viewAll: 'View all {n} photos', openInGallery: 'Open in the gallery', sequence: 'Photos',
    next: 'Next project', nextNav: 'Another project', back: 'All projects',
  },
  gallery: {
    intro: 'Photographs of completed projects. Select a photo to see it full size with its description; use the arrow keys to move on.',
    filter: 'Filter', category: 'Category', year: 'Year', allCategories: 'All', allYears: 'All years',
    view: 'View', raster: 'Grid', byProject: 'By project',
    status: '{n} {images} from {p} {projects}', projectsPlural: ['project', 'projects'],
    reset: 'Reset filters', loading: 'Loading photos',
    emptyTitle: 'No photos published yet.',
    emptyText: 'New photographs appear here once a project is completed and documented. Until then, you can find our work with descriptions under Projects.',
    toProjects: 'Go to projects',
    filterEmptyTitle: 'No photos for {what}.', filterEmptyFallback: 'this selection', filterEmptyYear: 'from {year}',
    filterEmptyText: 'Choose another category or year.',
    errorTitle: 'The photos could not be loaded.',
    errorText: 'The image server did not respond. Check your connection and reload the page.',
    reload: 'Reload page',
    moreTitle: 'Want to see a project in detail?', moreLink: 'All projects with descriptions',
    location: 'Location', count: 'Photos', grid: 'Photos',
  },
  lightbox: { dialog: 'Image viewer', close: 'Close', prev: 'Previous image', next: 'Next image', toProject: 'Go to project' },
  services: {
    intro: 'We accompany building projects from the first consultation through design and permits to site supervision, for new buildings and existing ones alike.',
    list: 'Services', timeline: 'Time frame', features: 'Focus', process: 'Process',
    processIntro: 'Planning follows fixed steps, so you always know what comes next.',
    kinds: 'Building types', kindsIntro: 'We regularly design these types of buildings.',
    fallback: [
      { id: 'neubau', title: 'New build', description: 'Houses, apartment buildings and commercial buildings, from site analysis to handover.' },
      { id: 'altbausanierung', title: 'Renovation', description: 'Survey, renovation concept and energy upgrade, matched to the fabric and building physics of the house.' },
      { id: 'denkmalschutz', title: 'Listed buildings', description: 'Design and permits agreed with the heritage authority, so that a conversion keeps the character of the building.' },
      { id: 'innenarchitektur', title: 'Interior design', description: 'Space planning, materials and lighting for offices, medical practices and homes.' },
    ],
    ctaTitle: 'Planning a new build or a conversion?',
    ctaText: 'Tell us briefly about your project. We will get back to you to arrange a first meeting.',
    ctaButton: 'Send an enquiry',
  },
  about: {
    lead: `Braun & Eyer Architects is an architecture office in ${SITE.address.city}. Christian F. Braun and Patric Eyer founded the office in ${Y} and run it together.`,
    text: 'We design new buildings and conversions for private and commercial clients, renovate old and listed buildings and design interiors. Both partners are members of the Saarland Chamber of Architects.',
    facts: 'The office at a glance', founded: 'Founded', seat: 'Based in', partners: 'Partners', chamber: 'Chamber',
    team: 'Team', email: 'Email', phone: 'Phone',
    ctaTitle: 'Get to know us.',
    ctaText: 'The easiest way is a first conversation about your project, by phone or at our office.',
    ctaButton: 'Get in touch', projectsLink: 'View projects',
  },
  contact: {
    intro: 'Call us, send an email or use the form. We will get back to you.',
    address: 'Address', phone: 'Phone', fax: 'Fax', email: 'Email', hours: 'Office hours', closed: 'closed',
    route: 'Open the route in Google Maps', online: 'Online',
    form: {
      title: 'Enquiry', name: 'Name', email: 'Email', phone: 'Phone', optional: '(optional)',
      projectType: 'Type of project', select: 'Please choose',
      types: {
        neubau: 'New build', altbausanierung: 'Renovation', denkmalschutz: 'Listed building',
        innenarchitektur: 'Interior design', energieberatung: 'Energy consulting', beratung: 'Consultation', sonstiges: 'Other',
      },
      timeline: 'Time frame', timelineHint: 'for example: start of construction next spring',
      message: 'Message', messageHint: 'What is it about? New build or existing building, location, size.',
      required: 'Fields without a note are required.',
      privacy: 'We only use your details to answer your enquiry. More in the',
      privacyLink: 'privacy policy',
      submit: 'Send enquiry', sending: 'Sending …',
      successTitle: 'Thank you, your message has arrived.', successText: 'We will get back to you as soon as possible.',
      another: 'Write another message', summary: 'Please check the marked fields.',
      errName: 'Please enter your name.', errEmail: 'Please enter your email address.',
      errEmailInvalid: 'This email address is incomplete, for example name@example.com.',
      errMessage: 'Please write a short message.',
      errSubmit: 'The message could not be sent. Please try again or write directly to',
    },
  },
  legal: {
    imprintAside: 'Information pursuant to § 5 DDG (German Digital Services Act). The legal text is provided in German.',
    privacyAside: 'Which data this website processes, why, and what rights you have. The legal text is provided in German.',
  },
  cookie: {
    title: 'Cookie settings',
    text: 'We use cookies to improve your experience on our website and to collect anonymous statistics. You can change your settings at any time in the footer.',
    privacyLink: 'Privacy policy', necessaryOnly: 'Necessary only', settings: 'Settings', acceptAll: 'Accept all',
    save: 'Save selection', group: 'Cookie categories',
    necessary: 'Necessary cookies', necessaryText: 'These cookies are required for the basic functions of the website and cannot be disabled.',
    analytics: 'Analytics cookies', analyticsText: 'Help us understand how visitors interact with our website by collecting anonymous information.',
    marketing: 'Marketing cookies', marketingText: 'Used to show visitors relevant advertising and marketing campaigns.',
  },
};

const fr = {
  common: {
    skip: 'Aller au contenu', menu: 'Menu', close: 'Fermer', language: 'Langue', mainNav: 'Navigation principale',
    homeLabel: 'Braun & Eyer Architectes, aller à l’accueil', breadcrumbs: 'Fil d’Ariane',
    images: ['photo', 'photos'], imageN: 'Photo {n}', imageOf: 'Photo {n} sur {total}', enlarge: 'Agrandir : {label}',
    viewProject: 'Voir le projet',
  },
  categories: { neubau: 'Construction neuve', altbausanierung: 'Rénovation', denkmalschutz: 'Monuments historiques', innenarchitektur: 'Architecture intérieure' },
  footer: { office: 'Agence', contact: 'Contact', pages: 'Pages', nav: 'Pied de page', cookies: 'Paramètres des cookies' },
  home: {
    intro: 'Nous concevons des bâtiments neufs, rénovons l’existant et accompagnons les transformations de monuments protégés, de la première esquisse au suivi de chantier.',
    since: `Agence d’architecture à ${SITE.address.city}, depuis ${Y}`,
    heroLink: 'Voir les projets', playVideo: 'Lire la vidéo',
    selected: 'Projets choisis', allProjects: 'Tous les projets',
    services: 'Prestations',
    servicesIntro: 'Nous assurons la conception du premier conseil au suivi de chantier, en passant par le projet et le permis de construire.',
    servicesMore: 'Prestations et déroulement en détail',
    office: 'L’agence',
    officeLead: `Braun & Eyer Architectes est une agence d’architecture à ${SITE.address.city}, fondée en ${Y}. Christian F. Braun et Patric Eyer la dirigent ensemble.`,
    officeMore: 'En savoir plus sur l’agence', team: 'Équipe',
    contactTitle: 'Parlons de votre projet.',
    contactText: 'Appelez-nous ou décrivez-nous brièvement votre projet : construction neuve ou existant, lieu, calendrier souhaité.',
    contactButton: 'Envoyer une demande',
    hero: {
      label: 'Projets en images', carousel: 'carrousel', slide: 'diapositive', slideOf: '{n} sur {total}',
      prev: 'Diapositive précédente', next: 'Diapositive suivante', goTo: 'Afficher la diapositive {n}',
      pause: 'Mettre en pause le défilement automatique', play: 'Lancer le défilement automatique',
      work: 'Nos réalisations', contact: 'Contact', completed: 'Achèvement {year}',
    },
  },
  entry: { label: 'Bienvenue', enterHint: 'Accéder au site' },
  typo: {
    architecture: 'architecture', design: 'design', innovation: 'innovation', vision: 'vision', space: 'espace',
    build: 'construire', renovate: 'rénovation', heritage: 'patrimoine', contact: 'contact', dialogue: 'dialogue',
  },
  projects: {
    intro: 'Une sélection de projets réalisés : construction neuve, rénovation et architecture intérieure.',
    filterLabel: 'Catégorie', all: 'Tous',
    empty: 'Aucun projet n’est publié pour le moment.', emptyCategory: 'Aucun projet n’est encore publié dans cette catégorie.',
    error: 'Les projets n’ont pas pu être chargés. Veuillez recharger la page.', reload: 'Recharger la page',
    toGallery: 'Toutes les photos dans la galerie', galleryHint: 'Toutes les photographies d’un coup d’œil, filtrées par catégorie et par année.',
  },
  project: {
    facts: 'Données du projet', description: 'Description du projet', location: 'Lieu', year: 'Année', category: 'Catégorie',
    area: 'Surface', status: 'Statut', count: 'Photos', viewAll: 'Voir les {n} photos', openInGallery: 'Ouvrir dans la galerie',
    sequence: 'Photos', next: 'Projet suivant', nextNav: 'Autre projet', back: 'Tous les projets',
  },
  gallery: {
    intro: 'Photographies de projets réalisés. Une photo s’ouvre en grand avec sa description ; les flèches du clavier permettent de passer à la suivante.',
    filter: 'Filtre', category: 'Catégorie', year: 'Année', allCategories: 'Toutes', allYears: 'Toutes les années',
    view: 'Affichage', raster: 'Grille', byProject: 'Par projet',
    status: '{n} {images} de {p} {projects}', projectsPlural: ['projet', 'projets'],
    reset: 'Réinitialiser les filtres', loading: 'Chargement des photos',
    emptyTitle: 'Aucune photo publiée pour l’instant.',
    emptyText: 'Les nouvelles photographies apparaissent ici dès qu’un projet est achevé et documenté. En attendant, nos réalisations sont décrites sous Projets.',
    toProjects: 'Voir les projets',
    filterEmptyTitle: 'Aucune photo pour {what}.', filterEmptyFallback: 'cette sélection', filterEmptyYear: 'de {year}',
    filterEmptyText: 'Choisissez une autre catégorie ou une autre année.',
    errorTitle: 'Les photos n’ont pas pu être chargées.',
    errorText: 'Le serveur d’images n’a pas répondu. Vérifiez votre connexion et rechargez la page.',
    reload: 'Recharger la page', moreTitle: 'Voir un projet en détail ?', moreLink: 'Tous les projets avec description',
    location: 'Lieu', count: 'Photos', grid: 'Photos',
  },
  lightbox: { dialog: 'Visionneuse', close: 'Fermer', prev: 'Image précédente', next: 'Image suivante', toProject: 'Voir le projet' },
  services: {
    intro: 'Nous accompagnons les projets de construction du premier conseil au suivi de chantier, en passant par la conception et les autorisations, dans le neuf comme dans l’existant.',
    list: 'Prestations', timeline: 'Durée', features: 'Points forts', process: 'Déroulement',
    processIntro: 'La conception suit des étapes définies : vous savez toujours ce qui vient ensuite.',
    kinds: 'Types de bâtiments', kindsIntro: 'Nous concevons régulièrement ces types de bâtiments.',
    fallback: [
      { id: 'neubau', title: 'Construction neuve', description: 'Maisons, immeubles d’habitation et bâtiments commerciaux, de l’analyse du site à la réception.' },
      { id: 'altbausanierung', title: 'Rénovation', description: 'Relevé, concept de rénovation et rénovation énergétique, adaptés à la substance et à la physique du bâtiment.' },
      { id: 'denkmalschutz', title: 'Monuments historiques', description: 'Conception et autorisations en accord avec l’autorité du patrimoine, pour préserver le caractère du bâtiment.' },
      { id: 'innenarchitektur', title: 'Architecture intérieure', description: 'Aménagement, matériaux et éclairage pour bureaux, cabinets médicaux et logements.' },
    ],
    ctaTitle: 'Vous prévoyez une construction ou une transformation ?',
    ctaText: 'Décrivez-nous brièvement votre projet. Nous vous recontactons pour convenir d’un premier entretien.',
    ctaButton: 'Envoyer une demande',
  },
  about: {
    lead: `Braun & Eyer Architectes est une agence d’architecture à ${SITE.address.city}. Christian F. Braun et Patric Eyer l’ont fondée en ${Y} et la dirigent ensemble.`,
    text: 'Nous concevons des bâtiments neufs et des transformations pour des maîtres d’ouvrage privés et professionnels, rénovons des bâtiments anciens et protégés et aménageons des intérieurs. Les deux associés sont membres de l’Ordre des architectes de la Sarre.',
    facts: 'L’agence en bref', founded: 'Fondée', seat: 'Siège', partners: 'Associés', chamber: 'Ordre',
    team: 'Équipe', email: 'E-mail', phone: 'Téléphone',
    ctaTitle: 'Faisons connaissance.', ctaText: 'Le plus simple : un premier entretien sur votre projet, par téléphone ou à l’agence.',
    ctaButton: 'Nous contacter', projectsLink: 'Voir les projets',
  },
  contact: {
    intro: 'Appelez-nous, écrivez-nous un e-mail ou utilisez le formulaire. Nous vous répondrons.',
    address: 'Adresse', phone: 'Téléphone', fax: 'Fax', email: 'E-mail', hours: 'Horaires', closed: 'fermé',
    route: 'Ouvrir l’itinéraire dans Google Maps', online: 'En ligne',
    form: {
      title: 'Demande', name: 'Nom', email: 'E-mail', phone: 'Téléphone', optional: '(facultatif)',
      projectType: 'Type de projet', select: 'Veuillez choisir',
      types: {
        neubau: 'Construction neuve', altbausanierung: 'Rénovation', denkmalschutz: 'Monument historique',
        innenarchitektur: 'Architecture intérieure', energieberatung: 'Conseil énergétique', beratung: 'Conseil', sonstiges: 'Autre',
      },
      timeline: 'Calendrier', timelineHint: 'par exemple : début des travaux au printemps',
      message: 'Message', messageHint: 'De quoi s’agit-il ? Neuf ou existant, lieu, surface.',
      required: 'Les champs sans mention sont obligatoires.',
      privacy: 'Nous utilisons vos données uniquement pour répondre à votre demande. Plus d’informations dans la',
      privacyLink: 'politique de confidentialité',
      submit: 'Envoyer la demande', sending: 'Envoi …',
      successTitle: 'Merci, votre message est bien arrivé.', successText: 'Nous vous répondrons dès que possible.',
      another: 'Écrire un autre message', summary: 'Veuillez vérifier les champs signalés.',
      errName: 'Veuillez indiquer votre nom.', errEmail: 'Veuillez indiquer votre adresse e-mail.',
      errEmailInvalid: 'Cette adresse e-mail est incomplète, par exemple nom@exemple.fr.',
      errMessage: 'Veuillez écrire un court message.',
      errSubmit: 'Le message n’a pas pu être envoyé. Veuillez réessayer ou écrire directement à',
    },
  },
  legal: {
    imprintAside: 'Informations selon le § 5 DDG (loi allemande sur les services numériques). Le texte juridique est rédigé en allemand.',
    privacyAside: 'Quelles données ce site traite, pourquoi et quels sont vos droits. Le texte juridique est rédigé en allemand.',
  },
  cookie: {
    title: 'Paramètres des cookies',
    text: 'Nous utilisons des cookies pour améliorer votre expérience sur notre site et collecter des statistiques anonymes. Vous pouvez modifier vos paramètres à tout moment dans le pied de page.',
    privacyLink: 'Politique de confidentialité', necessaryOnly: 'Nécessaires uniquement', settings: 'Paramètres', acceptAll: 'Tout accepter',
    save: 'Enregistrer la sélection', group: 'Catégories de cookies',
    necessary: 'Cookies nécessaires', necessaryText: 'Ces cookies sont indispensables au fonctionnement du site et ne peuvent pas être désactivés.',
    analytics: 'Cookies d’analyse', analyticsText: 'Nous aident à comprendre comment les visiteurs utilisent notre site, grâce à des informations anonymes.',
    marketing: 'Cookies marketing', marketingText: 'Servent à proposer aux visiteurs des publicités et campagnes pertinentes.',
  },
};

const it = {
  common: {
    skip: 'Vai al contenuto', menu: 'Menu', close: 'Chiudi', language: 'Lingua', mainNav: 'Navigazione principale',
    homeLabel: 'Braun & Eyer Architetti, vai alla home page', breadcrumbs: 'Percorso',
    images: ['foto', 'foto'], imageN: 'Foto {n}', imageOf: 'Foto {n} di {total}', enlarge: 'Ingrandisci: {label}',
    viewProject: 'Vedi il progetto',
  },
  categories: { neubau: 'Nuova costruzione', altbausanierung: 'Ristrutturazione', denkmalschutz: 'Edifici vincolati', innenarchitektur: 'Architettura d’interni' },
  footer: { office: 'Studio', contact: 'Contatti', pages: 'Pagine', nav: 'Piè di pagina', cookies: 'Impostazioni cookie' },
  home: {
    intro: 'Progettiamo nuovi edifici, ristrutturiamo l’esistente e seguiamo trasformazioni di edifici vincolati, dal primo schizzo alla direzione lavori.',
    since: `Studio di architettura a ${SITE.address.city}, dal ${Y}`,
    heroLink: 'Vedi i progetti', playVideo: 'Riproduci video',
    selected: 'Progetti scelti', allProjects: 'Tutti i progetti',
    services: 'Servizi',
    servicesIntro: 'Seguiamo la progettazione dalla prima consulenza, attraverso progetto e permesso di costruire, fino alla direzione lavori.',
    servicesMore: 'Servizi e fasi nel dettaglio',
    office: 'Lo studio',
    officeLead: `Braun & Eyer Architetti è uno studio di architettura a ${SITE.address.city}, fondato nel ${Y}. Christian F. Braun e Patric Eyer lo dirigono insieme.`,
    officeMore: 'Di più sullo studio', team: 'Team',
    contactTitle: 'Parliamo del vostro progetto.',
    contactText: 'Chiamateci o scriveteci brevemente di cosa si tratta: nuova costruzione o esistente, luogo, tempi desiderati.',
    contactButton: 'Invia una richiesta',
    hero: {
      label: 'Progetti in immagini', carousel: 'carosello', slide: 'diapositiva', slideOf: '{n} di {total}',
      prev: 'Diapositiva precedente', next: 'Diapositiva successiva', goTo: 'Mostra la diapositiva {n}',
      pause: 'Metti in pausa la rotazione automatica', play: 'Avvia la rotazione automatica',
      work: 'I nostri lavori', contact: 'Contatti', completed: 'Completamento {year}',
    },
  },
  entry: { label: 'Benvenuti', enterHint: 'Vai al sito' },
  typo: {
    architecture: 'architettura', design: 'design', innovation: 'innovazione', vision: 'visione', space: 'spazio',
    build: 'costruire', renovate: 'restauro', heritage: 'patrimonio', contact: 'contatto', dialogue: 'dialogo',
  },
  projects: {
    intro: 'Una selezione di progetti realizzati: nuove costruzioni, ristrutturazioni e architettura d’interni.',
    filterLabel: 'Categoria', all: 'Tutti',
    empty: 'Al momento non ci sono progetti pubblicati.', emptyCategory: 'In questa categoria non ci sono ancora progetti pubblicati.',
    error: 'Non è stato possibile caricare i progetti. Ricaricate la pagina.', reload: 'Ricarica la pagina',
    toGallery: 'Tutte le foto nella galleria', galleryHint: 'Tutte le fotografie a colpo d’occhio, filtrate per categoria e anno.',
  },
  project: {
    facts: 'Dati del progetto', description: 'Descrizione del progetto', location: 'Luogo', year: 'Anno', category: 'Categoria',
    area: 'Superficie', status: 'Stato', count: 'Foto', viewAll: 'Vedi tutte le {n} foto', openInGallery: 'Apri nella galleria',
    sequence: 'Foto', next: 'Progetto successivo', nextNav: 'Altro progetto', back: 'Tutti i progetti',
  },
  gallery: {
    intro: 'Fotografie di progetti realizzati. Una foto si apre a schermo intero con la descrizione; con le frecce della tastiera si passa alla successiva.',
    filter: 'Filtro', category: 'Categoria', year: 'Anno', allCategories: 'Tutte', allYears: 'Tutti gli anni',
    view: 'Vista', raster: 'Griglia', byProject: 'Per progetto',
    status: '{n} {images} da {p} {projects}', projectsPlural: ['progetto', 'progetti'],
    reset: 'Azzera i filtri', loading: 'Caricamento delle foto',
    emptyTitle: 'Nessuna foto pubblicata finora.',
    emptyText: 'Le nuove fotografie compaiono qui non appena un progetto è completato e documentato. Nel frattempo trovate i nostri lavori con descrizione sotto Progetti.',
    toProjects: 'Vai ai progetti',
    filterEmptyTitle: 'Nessuna foto per {what}.', filterEmptyFallback: 'questa selezione', filterEmptyYear: 'del {year}',
    filterEmptyText: 'Scegliete un’altra categoria o un altro anno.',
    errorTitle: 'Non è stato possibile caricare le foto.',
    errorText: 'Il server delle immagini non ha risposto. Controllate la connessione e ricaricate la pagina.',
    reload: 'Ricarica la pagina', moreTitle: 'Volete vedere un progetto nel dettaglio?', moreLink: 'Tutti i progetti con descrizione',
    location: 'Luogo', count: 'Foto', grid: 'Foto',
  },
  lightbox: { dialog: 'Visualizzatore', close: 'Chiudi', prev: 'Immagine precedente', next: 'Immagine successiva', toProject: 'Vai al progetto' },
  services: {
    intro: 'Accompagniamo i progetti edilizi dalla prima consulenza, attraverso progettazione e autorizzazioni, fino alla direzione lavori, sia nel nuovo sia nell’esistente.',
    list: 'Servizi', timeline: 'Tempi', features: 'Punti chiave', process: 'Fasi',
    processIntro: 'La progettazione segue fasi definite: sapete sempre che cosa viene dopo.',
    kinds: 'Tipologie', kindsIntro: 'Progettiamo regolarmente questi tipi di edifici.',
    fallback: [
      { id: 'neubau', title: 'Nuova costruzione', description: 'Case, edifici plurifamiliari ed edifici commerciali, dall’analisi del sito al collaudo.' },
      { id: 'altbausanierung', title: 'Ristrutturazione', description: 'Rilievo, progetto di risanamento e riqualificazione energetica, calibrati sulla sostanza e sulla fisica dell’edificio.' },
      { id: 'denkmalschutz', title: 'Edifici vincolati', description: 'Progetto e autorizzazioni in accordo con la soprintendenza, perché la trasformazione conservi il carattere dell’edificio.' },
      { id: 'innenarchitektur', title: 'Architettura d’interni', description: 'Distribuzione degli spazi, materiali e luce per uffici, studi medici e abitazioni.' },
    ],
    ctaTitle: 'Progettate una nuova costruzione o una trasformazione?',
    ctaText: 'Descriveteci brevemente il vostro progetto. Vi ricontatteremo per fissare un primo incontro.',
    ctaButton: 'Invia una richiesta',
  },
  about: {
    lead: `Braun & Eyer Architetti è uno studio di architettura a ${SITE.address.city}. Christian F. Braun e Patric Eyer lo hanno fondato nel ${Y} e lo dirigono insieme.`,
    text: 'Progettiamo nuovi edifici e trasformazioni per committenti privati e aziende, ristrutturiamo edifici storici e vincolati e progettiamo interni. Entrambi i soci sono iscritti all’Ordine degli architetti del Saarland.',
    facts: 'Lo studio in breve', founded: 'Fondato', seat: 'Sede', partners: 'Soci', chamber: 'Ordine',
    team: 'Team', email: 'E-mail', phone: 'Telefono',
    ctaTitle: 'Conosciamoci.', ctaText: 'Il modo più semplice è un primo colloquio sul vostro progetto, al telefono o in studio.',
    ctaButton: 'Contattateci', projectsLink: 'Vedi i progetti',
  },
  contact: {
    intro: 'Chiamateci, scriveteci un’e-mail o usate il modulo. Vi risponderemo.',
    address: 'Indirizzo', phone: 'Telefono', fax: 'Fax', email: 'E-mail', hours: 'Orari dello studio', closed: 'chiuso',
    route: 'Apri il percorso in Google Maps', online: 'Online',
    form: {
      title: 'Richiesta', name: 'Nome', email: 'E-mail', phone: 'Telefono', optional: '(facoltativo)',
      projectType: 'Tipo di progetto', select: 'Scegliete',
      types: {
        neubau: 'Nuova costruzione', altbausanierung: 'Ristrutturazione', denkmalschutz: 'Edificio vincolato',
        innenarchitektur: 'Architettura d’interni', energieberatung: 'Consulenza energetica', beratung: 'Consulenza', sonstiges: 'Altro',
      },
      timeline: 'Tempi', timelineHint: 'per esempio: inizio lavori in primavera',
      message: 'Messaggio', messageHint: 'Di che cosa si tratta? Nuovo o esistente, luogo, dimensioni.',
      required: 'I campi senza indicazione sono obbligatori.',
      privacy: 'Usiamo i vostri dati solo per rispondere alla richiesta. Maggiori informazioni nell’',
      privacyLink: 'informativa sulla privacy',
      submit: 'Invia la richiesta', sending: 'Invio in corso …',
      successTitle: 'Grazie, il vostro messaggio è arrivato.', successText: 'Vi risponderemo il prima possibile.',
      another: 'Scrivi un altro messaggio', summary: 'Controllate i campi evidenziati.',
      errName: 'Indicate il vostro nome.', errEmail: 'Indicate il vostro indirizzo e-mail.',
      errEmailInvalid: 'Questo indirizzo e-mail è incompleto, per esempio nome@esempio.it.',
      errMessage: 'Scrivete un breve messaggio.',
      errSubmit: 'Non è stato possibile inviare il messaggio. Riprovate o scrivete direttamente a',
    },
  },
  legal: {
    imprintAside: 'Informazioni ai sensi del § 5 DDG (legge tedesca sui servizi digitali). Il testo legale è in tedesco.',
    privacyAside: 'Quali dati tratta questo sito, a quale scopo e quali diritti avete. Il testo legale è in tedesco.',
  },
  cookie: {
    title: 'Impostazioni cookie',
    text: 'Utilizziamo i cookie per migliorare la vostra esperienza sul sito e raccogliere statistiche anonime. Potete modificare le impostazioni in qualsiasi momento nel piè di pagina.',
    privacyLink: 'Informativa sulla privacy', necessaryOnly: 'Solo necessari', settings: 'Impostazioni', acceptAll: 'Accetta tutti',
    save: 'Salva la selezione', group: 'Categorie di cookie',
    necessary: 'Cookie necessari', necessaryText: 'Questi cookie sono indispensabili per le funzioni di base del sito e non possono essere disattivati.',
    analytics: 'Cookie di analisi', analyticsText: 'Ci aiutano a capire come i visitatori usano il sito raccogliendo informazioni anonime.',
    marketing: 'Cookie di marketing', marketingText: 'Servono a proporre ai visitatori pubblicità e campagne pertinenti.',
  },
};

const es = {
  common: {
    skip: 'Ir al contenido', menu: 'Menú', close: 'Cerrar', language: 'Idioma', mainNav: 'Navegación principal',
    homeLabel: 'Braun & Eyer Arquitectos, ir a la página de inicio', breadcrumbs: 'Ruta de navegación',
    images: ['foto', 'fotos'], imageN: 'Foto {n}', imageOf: 'Foto {n} de {total}', enlarge: 'Ampliar: {label}',
    viewProject: 'Ver el proyecto',
  },
  categories: { neubau: 'Obra nueva', altbausanierung: 'Rehabilitación', denkmalschutz: 'Edificios protegidos', innenarchitektur: 'Interiorismo' },
  footer: { office: 'Estudio', contact: 'Contacto', pages: 'Páginas', nav: 'Pie de página', cookies: 'Configuración de cookies' },
  home: {
    intro: 'Proyectamos edificios nuevos, rehabilitamos edificios existentes y acompañamos reformas de edificios protegidos, desde el primer boceto hasta la dirección de obra.',
    since: `Estudio de arquitectura en ${SITE.address.city}, desde ${Y}`,
    heroLink: 'Ver proyectos', playVideo: 'Reproducir vídeo',
    selected: 'Proyectos seleccionados', allProjects: 'Todos los proyectos',
    services: 'Servicios',
    servicesIntro: 'Nos ocupamos del proyecto desde la primera consulta, pasando por el diseño y la licencia de obra, hasta la dirección de obra.',
    servicesMore: 'Servicios y proceso en detalle',
    office: 'El estudio',
    officeLead: `Braun & Eyer Arquitectos es un estudio de arquitectura en ${SITE.address.city}, fundado en ${Y}. Christian F. Braun y Patric Eyer lo dirigen juntos.`,
    officeMore: 'Más sobre el estudio', team: 'Equipo',
    contactTitle: 'Hablemos de su proyecto.',
    contactText: 'Llámenos o escríbanos brevemente de qué se trata: obra nueva o existente, lugar, plazo deseado.',
    contactButton: 'Enviar una consulta',
    hero: {
      label: 'Proyectos en imágenes', carousel: 'carrusel', slide: 'diapositiva', slideOf: '{n} de {total}',
      prev: 'Diapositiva anterior', next: 'Diapositiva siguiente', goTo: 'Mostrar la diapositiva {n}',
      pause: 'Pausar la rotación automática', play: 'Iniciar la rotación automática',
      work: 'Nuestros trabajos', contact: 'Contacto', completed: 'Finalización {year}',
    },
  },
  entry: { label: 'Bienvenidos', enterHint: 'Ir al sitio web' },
  typo: {
    architecture: 'arquitectura', design: 'diseño', innovation: 'innovación', vision: 'visión', space: 'espacio',
    build: 'construir', renovate: 'rehabilitar', heritage: 'patrimonio', contact: 'contacto', dialogue: 'diálogo',
  },
  projects: {
    intro: 'Una selección de proyectos realizados: obra nueva, rehabilitación e interiorismo.',
    filterLabel: 'Categoría', all: 'Todos',
    empty: 'En este momento no hay proyectos publicados.', emptyCategory: 'Todavía no hay proyectos publicados en esta categoría.',
    error: 'No se han podido cargar los proyectos. Vuelva a cargar la página.', reload: 'Volver a cargar',
    toGallery: 'Todas las fotos en la galería', galleryHint: 'Todas las fotografías de un vistazo, filtradas por categoría y año.',
  },
  project: {
    facts: 'Datos del proyecto', description: 'Descripción del proyecto', location: 'Lugar', year: 'Año', category: 'Categoría',
    area: 'Superficie', status: 'Estado', count: 'Fotos', viewAll: 'Ver las {n} fotos', openInGallery: 'Abrir en la galería',
    sequence: 'Fotos', next: 'Siguiente proyecto', nextNav: 'Otro proyecto', back: 'Todos los proyectos',
  },
  gallery: {
    intro: 'Fotografías de proyectos realizados. Una foto se abre a tamaño completo con su descripción; con las flechas del teclado pasa a la siguiente.',
    filter: 'Filtro', category: 'Categoría', year: 'Año', allCategories: 'Todas', allYears: 'Todos los años',
    view: 'Vista', raster: 'Cuadrícula', byProject: 'Por proyecto',
    status: '{n} {images} de {p} {projects}', projectsPlural: ['proyecto', 'proyectos'],
    reset: 'Restablecer filtros', loading: 'Cargando fotos',
    emptyTitle: 'Todavía no hay fotos publicadas.',
    emptyText: 'Las nuevas fotografías aparecen aquí en cuanto un proyecto se termina y se documenta. Mientras tanto, encontrará nuestros trabajos con descripción en Proyectos.',
    toProjects: 'Ir a los proyectos',
    filterEmptyTitle: 'No hay fotos para {what}.', filterEmptyFallback: 'esta selección', filterEmptyYear: 'de {year}',
    filterEmptyText: 'Elija otra categoría u otro año.',
    errorTitle: 'No se han podido cargar las fotos.',
    errorText: 'El servidor de imágenes no ha respondido. Compruebe su conexión y vuelva a cargar la página.',
    reload: 'Volver a cargar', moreTitle: '¿Quiere ver un proyecto en detalle?', moreLink: 'Todos los proyectos con descripción',
    location: 'Lugar', count: 'Fotos', grid: 'Fotos',
  },
  lightbox: { dialog: 'Visor de imágenes', close: 'Cerrar', prev: 'Imagen anterior', next: 'Imagen siguiente', toProject: 'Ir al proyecto' },
  services: {
    intro: 'Acompañamos proyectos de construcción desde la primera consulta, pasando por el diseño y las licencias, hasta la dirección de obra, tanto en obra nueva como en edificios existentes.',
    list: 'Servicios', timeline: 'Plazo', features: 'Aspectos clave', process: 'Proceso',
    processIntro: 'El proyecto sigue pasos definidos: siempre sabe qué viene después.',
    kinds: 'Tipos de edificio', kindsIntro: 'Proyectamos con regularidad estos tipos de edificios.',
    fallback: [
      { id: 'neubau', title: 'Obra nueva', description: 'Viviendas, edificios plurifamiliares y edificios comerciales, desde el análisis del solar hasta la recepción.' },
      { id: 'altbausanierung', title: 'Rehabilitación', description: 'Levantamiento, concepto de rehabilitación y mejora energética, adaptados a la sustancia y la física del edificio.' },
      { id: 'denkmalschutz', title: 'Edificios protegidos', description: 'Proyecto y licencias acordados con la autoridad de patrimonio, para que la reforma conserve el carácter del edificio.' },
      { id: 'innenarchitektur', title: 'Interiorismo', description: 'Distribución, materiales e iluminación para oficinas, consultas médicas y viviendas.' },
    ],
    ctaTitle: '¿Planea una obra nueva o una reforma?',
    ctaText: 'Descríbanos brevemente su proyecto. Le contactaremos para acordar una primera reunión.',
    ctaButton: 'Enviar una consulta',
  },
  about: {
    lead: `Braun & Eyer Arquitectos es un estudio de arquitectura en ${SITE.address.city}. Christian F. Braun y Patric Eyer lo fundaron en ${Y} y lo dirigen juntos.`,
    text: 'Proyectamos edificios nuevos y reformas para clientes particulares y empresas, rehabilitamos edificios antiguos y protegidos y diseñamos interiores. Ambos socios son miembros del Colegio de Arquitectos del Sarre.',
    facts: 'El estudio en breve', founded: 'Fundado', seat: 'Sede', partners: 'Socios', chamber: 'Colegio',
    team: 'Equipo', email: 'Correo electrónico', phone: 'Teléfono',
    ctaTitle: 'Conózcanos.', ctaText: 'Lo más sencillo es una primera conversación sobre su proyecto, por teléfono o en nuestro estudio.',
    ctaButton: 'Contactar', projectsLink: 'Ver proyectos',
  },
  contact: {
    intro: 'Llámenos, escríbanos un correo o utilice el formulario. Le responderemos.',
    address: 'Dirección', phone: 'Teléfono', fax: 'Fax', email: 'Correo electrónico', hours: 'Horario', closed: 'cerrado',
    route: 'Abrir la ruta en Google Maps', online: 'En línea',
    form: {
      title: 'Consulta', name: 'Nombre', email: 'Correo electrónico', phone: 'Teléfono', optional: '(opcional)',
      projectType: 'Tipo de proyecto', select: 'Elija una opción',
      types: {
        neubau: 'Obra nueva', altbausanierung: 'Rehabilitación', denkmalschutz: 'Edificio protegido',
        innenarchitektur: 'Interiorismo', energieberatung: 'Asesoría energética', beratung: 'Asesoría', sonstiges: 'Otro',
      },
      timeline: 'Plazo', timelineHint: 'por ejemplo: inicio de obra en primavera',
      message: 'Mensaje', messageHint: '¿De qué se trata? Obra nueva o existente, lugar, tamaño.',
      required: 'Los campos sin indicación son obligatorios.',
      privacy: 'Solo usamos sus datos para responder a su consulta. Más información en la',
      privacyLink: 'política de privacidad',
      submit: 'Enviar consulta', sending: 'Enviando …',
      successTitle: 'Gracias, su mensaje ha llegado.', successText: 'Le responderemos lo antes posible.',
      another: 'Escribir otro mensaje', summary: 'Revise los campos marcados.',
      errName: 'Indique su nombre.', errEmail: 'Indique su correo electrónico.',
      errEmailInvalid: 'Este correo electrónico está incompleto, por ejemplo nombre@ejemplo.es.',
      errMessage: 'Escriba un mensaje breve.',
      errSubmit: 'No se ha podido enviar el mensaje. Inténtelo de nuevo o escriba directamente a',
    },
  },
  legal: {
    imprintAside: 'Información según el § 5 DDG (ley alemana de servicios digitales). El texto legal está en alemán.',
    privacyAside: 'Qué datos trata este sitio, con qué fin y qué derechos tiene. El texto legal está en alemán.',
  },
  cookie: {
    title: 'Configuración de cookies',
    text: 'Utilizamos cookies para mejorar su experiencia en nuestro sitio y recopilar estadísticas anónimas. Puede cambiar la configuración en cualquier momento en el pie de página.',
    privacyLink: 'Política de privacidad', necessaryOnly: 'Solo necesarias', settings: 'Configuración', acceptAll: 'Aceptar todas',
    save: 'Guardar selección', group: 'Categorías de cookies',
    necessary: 'Cookies necesarias', necessaryText: 'Estas cookies son imprescindibles para las funciones básicas del sitio y no se pueden desactivar.',
    analytics: 'Cookies de análisis', analyticsText: 'Nos ayudan a entender cómo interactúan los visitantes con el sitio, recopilando información anónima.',
    marketing: 'Cookies de marketing', marketingText: 'Se utilizan para ofrecer a los visitantes publicidad y campañas relevantes.',
  },
};

const pt = {
  common: {
    skip: 'Saltar para o conteúdo', menu: 'Menu', close: 'Fechar', language: 'Idioma', mainNav: 'Navegação principal',
    homeLabel: 'Braun & Eyer Arquitetos, ir para a página inicial', breadcrumbs: 'Caminho de navegação',
    images: ['fotografia', 'fotografias'], imageN: 'Fotografia {n}', imageOf: 'Fotografia {n} de {total}', enlarge: 'Ampliar: {label}',
    viewProject: 'Ver o projeto',
  },
  categories: { neubau: 'Construção nova', altbausanierung: 'Reabilitação', denkmalschutz: 'Património classificado', innenarchitektur: 'Arquitetura de interiores' },
  footer: { office: 'Atelier', contact: 'Contacto', pages: 'Páginas', nav: 'Rodapé', cookies: 'Definições de cookies' },
  home: {
    intro: 'Projetamos edifícios novos, reabilitamos edifícios existentes e acompanhamos intervenções em património classificado, do primeiro esboço ao acompanhamento da obra.',
    since: `Atelier de arquitetura em ${SITE.address.city}, desde ${Y}`,
    heroLink: 'Ver projetos', playVideo: 'Reproduzir vídeo',
    selected: 'Projetos selecionados', allProjects: 'Todos os projetos',
    services: 'Serviços',
    servicesIntro: 'Tratamos do projeto desde a primeira consulta, passando pelo desenho e pelo licenciamento, até ao acompanhamento da obra.',
    servicesMore: 'Serviços e processo em detalhe',
    office: 'O atelier',
    officeLead: `A Braun & Eyer Arquitetos é um atelier de arquitetura em ${SITE.address.city}, fundado em ${Y}. Christian F. Braun e Patric Eyer dirigem o atelier em conjunto.`,
    officeMore: 'Mais sobre o atelier', team: 'Equipa',
    contactTitle: 'Fale connosco sobre o seu projeto.',
    contactText: 'Telefone-nos ou escreva-nos brevemente do que se trata: construção nova ou existente, local, prazo pretendido.',
    contactButton: 'Enviar um pedido',
    hero: {
      label: 'Projetos em imagens', carousel: 'carrossel', slide: 'diapositivo', slideOf: '{n} de {total}',
      prev: 'Diapositivo anterior', next: 'Diapositivo seguinte', goTo: 'Mostrar o diapositivo {n}',
      pause: 'Pausar a rotação automática', play: 'Iniciar a rotação automática',
      work: 'Os nossos trabalhos', contact: 'Contacto', completed: 'Conclusão {year}',
    },
  },
  entry: { label: 'Bem-vindo', enterHint: 'Ir para o sítio' },
  typo: {
    architecture: 'arquitetura', design: 'design', innovation: 'inovação', vision: 'visão', space: 'espaço',
    build: 'construir', renovate: 'reabilitar', heritage: 'património', contact: 'contacto', dialogue: 'diálogo',
  },
  projects: {
    intro: 'Uma seleção de projetos realizados: construção nova, reabilitação e arquitetura de interiores.',
    filterLabel: 'Categoria', all: 'Todos',
    empty: 'De momento não há projetos publicados.', emptyCategory: 'Ainda não há projetos publicados nesta categoria.',
    error: 'Não foi possível carregar os projetos. Volte a carregar a página.', reload: 'Recarregar a página',
    toGallery: 'Todas as fotografias na galeria', galleryHint: 'Todas as fotografias num relance, filtradas por categoria e ano.',
  },
  project: {
    facts: 'Dados do projeto', description: 'Descrição do projeto', location: 'Local', year: 'Ano', category: 'Categoria',
    area: 'Área', status: 'Estado', count: 'Fotografias', viewAll: 'Ver as {n} fotografias', openInGallery: 'Abrir na galeria',
    sequence: 'Fotografias', next: 'Projeto seguinte', nextNav: 'Outro projeto', back: 'Todos os projetos',
  },
  gallery: {
    intro: 'Fotografias de projetos realizados. Uma fotografia abre em tamanho grande com a descrição; com as setas do teclado passa à seguinte.',
    filter: 'Filtro', category: 'Categoria', year: 'Ano', allCategories: 'Todas', allYears: 'Todos os anos',
    view: 'Vista', raster: 'Grelha', byProject: 'Por projeto',
    status: '{n} {images} de {p} {projects}', projectsPlural: ['projeto', 'projetos'],
    reset: 'Repor filtros', loading: 'A carregar fotografias',
    emptyTitle: 'Ainda não há fotografias publicadas.',
    emptyText: 'As novas fotografias aparecem aqui assim que um projeto é concluído e documentado. Até lá, encontra os nossos trabalhos com descrição em Projetos.',
    toProjects: 'Ir para os projetos',
    filterEmptyTitle: 'Não há fotografias para {what}.', filterEmptyFallback: 'esta seleção', filterEmptyYear: 'de {year}',
    filterEmptyText: 'Escolha outra categoria ou outro ano.',
    errorTitle: 'Não foi possível carregar as fotografias.',
    errorText: 'O servidor de imagens não respondeu. Verifique a ligação e volte a carregar a página.',
    reload: 'Recarregar a página', moreTitle: 'Quer ver um projeto em detalhe?', moreLink: 'Todos os projetos com descrição',
    location: 'Local', count: 'Fotografias', grid: 'Fotografias',
  },
  lightbox: { dialog: 'Visualizador', close: 'Fechar', prev: 'Imagem anterior', next: 'Imagem seguinte', toProject: 'Ir para o projeto' },
  services: {
    intro: 'Acompanhamos projetos de construção desde a primeira consulta, passando pelo desenho e pelo licenciamento, até ao acompanhamento da obra, tanto em construção nova como em edifícios existentes.',
    list: 'Serviços', timeline: 'Prazo', features: 'Pontos-chave', process: 'Processo',
    processIntro: 'O projeto segue etapas definidas: sabe sempre o que vem a seguir.',
    kinds: 'Tipologias', kindsIntro: 'Projetamos regularmente estes tipos de edifícios.',
    fallback: [
      { id: 'neubau', title: 'Construção nova', description: 'Moradias, edifícios de habitação coletiva e edifícios comerciais, da análise do terreno à receção da obra.' },
      { id: 'altbausanierung', title: 'Reabilitação', description: 'Levantamento, conceito de reabilitação e melhoria energética, ajustados à substância e à física do edifício.' },
      { id: 'denkmalschutz', title: 'Património classificado', description: 'Projeto e licenciamento articulados com a autoridade do património, para que a intervenção preserve o caráter do edifício.' },
      { id: 'innenarchitektur', title: 'Arquitetura de interiores', description: 'Organização do espaço, materiais e iluminação para escritórios, consultórios e habitações.' },
    ],
    ctaTitle: 'Está a planear uma construção nova ou uma remodelação?',
    ctaText: 'Descreva-nos brevemente o seu projeto. Entraremos em contacto para marcar uma primeira reunião.',
    ctaButton: 'Enviar um pedido',
  },
  about: {
    lead: `A Braun & Eyer Arquitetos é um atelier de arquitetura em ${SITE.address.city}. Christian F. Braun e Patric Eyer fundaram o atelier em ${Y} e dirigem-no em conjunto.`,
    text: 'Projetamos edifícios novos e remodelações para clientes particulares e empresas, reabilitamos edifícios antigos e classificados e projetamos interiores. Ambos os sócios são membros da Ordem dos Arquitetos do Sarre.',
    facts: 'O atelier em resumo', founded: 'Fundado', seat: 'Sede', partners: 'Sócios', chamber: 'Ordem',
    team: 'Equipa', email: 'E-mail', phone: 'Telefone',
    ctaTitle: 'Conheça-nos.', ctaText: 'O mais simples é uma primeira conversa sobre o seu projeto, por telefone ou no nosso atelier.',
    ctaButton: 'Contactar', projectsLink: 'Ver projetos',
  },
  contact: {
    intro: 'Telefone-nos, envie um e-mail ou use o formulário. Entraremos em contacto consigo.',
    address: 'Morada', phone: 'Telefone', fax: 'Fax', email: 'E-mail', hours: 'Horário', closed: 'fechado',
    route: 'Abrir o percurso no Google Maps', online: 'Online',
    form: {
      title: 'Pedido', name: 'Nome', email: 'E-mail', phone: 'Telefone', optional: '(opcional)',
      projectType: 'Tipo de projeto', select: 'Escolha uma opção',
      types: {
        neubau: 'Construção nova', altbausanierung: 'Reabilitação', denkmalschutz: 'Património classificado',
        innenarchitektur: 'Arquitetura de interiores', energieberatung: 'Consultoria energética', beratung: 'Consultoria', sonstiges: 'Outro',
      },
      timeline: 'Prazo', timelineHint: 'por exemplo: início da obra na primavera',
      message: 'Mensagem', messageHint: 'Do que se trata? Construção nova ou existente, local, dimensão.',
      required: 'Os campos sem indicação são obrigatórios.',
      privacy: 'Usamos os seus dados apenas para responder ao seu pedido. Mais informações na',
      privacyLink: 'política de privacidade',
      submit: 'Enviar pedido', sending: 'A enviar …',
      successTitle: 'Obrigado, a sua mensagem chegou.', successText: 'Responderemos assim que possível.',
      another: 'Escrever outra mensagem', summary: 'Verifique os campos assinalados.',
      errName: 'Indique o seu nome.', errEmail: 'Indique o seu endereço de e-mail.',
      errEmailInvalid: 'Este endereço de e-mail está incompleto, por exemplo nome@exemplo.pt.',
      errMessage: 'Escreva uma mensagem curta.',
      errSubmit: 'Não foi possível enviar a mensagem. Tente novamente ou escreva diretamente para',
    },
  },
  legal: {
    imprintAside: 'Informações nos termos do § 5 DDG (lei alemã dos serviços digitais). O texto jurídico está em alemão.',
    privacyAside: 'Que dados este sítio trata, para que fim e que direitos tem. O texto jurídico está em alemão.',
  },
  cookie: {
    title: 'Definições de cookies',
    text: 'Utilizamos cookies para melhorar a sua experiência no nosso sítio e recolher estatísticas anónimas. Pode alterar as definições a qualquer momento no rodapé.',
    privacyLink: 'Política de privacidade', necessaryOnly: 'Apenas necessários', settings: 'Definições', acceptAll: 'Aceitar todos',
    save: 'Guardar seleção', group: 'Categorias de cookies',
    necessary: 'Cookies necessários', necessaryText: 'Estes cookies são indispensáveis às funções básicas do sítio e não podem ser desativados.',
    analytics: 'Cookies de análise', analyticsText: 'Ajudam-nos a perceber como os visitantes utilizam o sítio, recolhendo informação anónima.',
    marketing: 'Cookies de marketing', marketingText: 'Servem para apresentar aos visitantes publicidade e campanhas relevantes.',
  },
};

export const UI_COPY = { de, en, fr, it, es, pt };

function isPlainObject(v) {
  return v && typeof v === 'object' && !Array.isArray(v);
}

function deepMerge(base, over) {
  if (!isPlainObject(over)) return over === undefined ? base : over;
  const out = { ...base };
  for (const key of Object.keys(over)) {
    out[key] = isPlainObject(base?.[key]) ? deepMerge(base[key], over[key]) : over[key];
  }
  return out;
}

const cache = {};

/** Copy for a language; any missing key falls back to German. */
export function getUiCopy(lang) {
  if (!cache[lang]) cache[lang] = lang === 'de' || !UI_COPY[lang] ? de : deepMerge(de, UI_COPY[lang]);
  return cache[lang];
}
