import path from 'path';
import fs from 'fs/promises';

/**
 * Upload whitelist shared by every multer instance (media library, team photos).
 *
 * A file is accepted only if BOTH its extension and its declared MIME type are
 * on the list and belong together. SVG, HTML, PDF and anything else are
 * rejected: files are served from /uploads on the API domain, and SVG/HTML
 * there would allow stored XSS. File names on disk are always generated by the
 * server; the client's name is only kept (sanitised) as metadata.
 */
export const IMAGE_TYPES = {
  '.jpg': ['image/jpeg', 'image/pjpeg'],
  '.jpeg': ['image/jpeg', 'image/pjpeg'],
  '.png': ['image/png'],
  '.webp': ['image/webp'],
  '.gif': ['image/gif'],
  '.avif': ['image/avif'],
};

export const VIDEO_TYPES = {
  '.mp4': ['video/mp4'],
  '.webm': ['video/webm'],
};

const MB = 1024 * 1024;

const intFromEnv = (name, fallback) => {
  const value = parseInt(process.env[name], 10);
  return Number.isFinite(value) && value > 0 ? value : fallback;
};

// Per-type size limits (bytes). MAX_FILE_SIZE is the older single setting and
// still applies to videos.
export const MAX_IMAGE_SIZE = intFromEnv('MAX_IMAGE_SIZE', 30 * MB);
export const MAX_VIDEO_SIZE = intFromEnv('MAX_VIDEO_SIZE', intFromEnv('MAX_FILE_SIZE', 200 * MB));

/** 'image' | 'video' | null, based on extension AND MIME type. */
export const classifyFile = (file, { allowVideo = true } = {}) => {
  const ext = path.extname(file.originalname || '').toLowerCase();
  const mime = String(file.mimetype || '').toLowerCase();

  if (IMAGE_TYPES[ext]?.includes(mime)) return 'image';
  if (allowVideo && VIDEO_TYPES[ext]?.includes(mime)) return 'video';
  return null;
};

/** Normalised, whitelisted extension for the server-side file name. */
export const safeExtension = (file) => path.extname(file.originalname || '').toLowerCase();

/** Server-generated file name: `<prefix>-<timestamp>-<random><ext>`. */
export const generateFilename = (prefix, file) => {
  const cleanPrefix = String(prefix || 'file').replace(/[^a-z0-9_-]/gi, '') || 'file';
  const uniqueSuffix = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
  return `${cleanPrefix}-${uniqueSuffix}${safeExtension(file)}`;
};

/** Original name kept as metadata only: no path segments, no control chars. */
export const sanitizeOriginalName = (name) => {
  const base = path.basename(String(name || '').replace(/\\/g, '/'));
  // eslint-disable-next-line no-control-regex
  return base.replace(/[\u0000-\u001f\u007f]/g, '').slice(0, 255) || 'upload';
};

const typeError = (allowVideo) => {
  const allowed = Object.keys(allowVideo ? { ...IMAGE_TYPES, ...VIDEO_TYPES } : IMAGE_TYPES)
    .map((e) => e.slice(1))
    .join(', ');
  const err = new Error(`File type not allowed. Allowed: ${allowed}`);
  err.status = 415;
  return err;
};

/** multer fileFilter factory. */
export const createFileFilter = ({ allowVideo = true } = {}) => (req, file, cb) => {
  file.originalname = sanitizeOriginalName(file.originalname);
  const kind = classifyFile(file, { allowVideo });
  if (!kind) {
    return cb(typeError(allowVideo));
  }
  file.uploadKind = kind;
  return cb(null, true);
};

/**
 * Express middleware placed after multer: multer only knows one global size
 * limit (the video limit), so images are checked here against MAX_IMAGE_SIZE.
 * Oversized files are deleted from disk and the request fails with 413.
 */
export const enforceTypeSizeLimits = async (req, res, next) => {
  const files = [
    ...(req.file ? [req.file] : []),
    ...(Array.isArray(req.files) ? req.files : []),
  ];

  const tooLarge = files.find((f) => (f.uploadKind === 'image' ? f.size > MAX_IMAGE_SIZE : f.size > MAX_VIDEO_SIZE));
  if (!tooLarge) return next();

  await Promise.all(
    files.filter((f) => f.path).map((f) => fs.unlink(f.path).catch(() => {}))
  );

  const limitMb = Math.round((tooLarge.uploadKind === 'image' ? MAX_IMAGE_SIZE : MAX_VIDEO_SIZE) / MB);
  return res.status(413).json({ error: `File too large (max. ${limitMb} MB for ${tooLarge.uploadKind}s)` });
};
